//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFS_Thesis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/tmp/IFS Images")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
            set {
                this["WorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int PopulationSize {
            get {
                return ((int)(this["PopulationSize"]));
            }
            set {
                this["PopulationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int NumberOfGenerations {
            get {
                return ((int)(this["NumberOfGenerations"]));
            }
            set {
                this["NumberOfGenerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ImageX {
            get {
                return ((int)(this["ImageX"]));
            }
            set {
                this["ImageX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ImageY {
            get {
                return ((int)(this["ImageY"]));
            }
            set {
                this["ImageY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ImageZ {
            get {
                return ((int)(this["ImageZ"]));
            }
            set {
                this["ImageZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public float N1IndividualsPercentage {
            get {
                return ((float)(this["N1IndividualsPercentage"]));
            }
            set {
                this["N1IndividualsPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public float N2IndividualsPercentage {
            get {
                return ((float)(this["N2IndividualsPercentage"]));
            }
            set {
                this["N2IndividualsPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public float N3IndividualsPercentage {
            get {
                return ((float)(this["N3IndividualsPercentage"]));
            }
            set {
                this["N3IndividualsPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float N4IndividualsPercentage {
            get {
                return ((float)(this["N4IndividualsPercentage"]));
            }
            set {
                this["N4IndividualsPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int PrcFitness {
            get {
                return ((int)(this["PrcFitness"]));
            }
            set {
                this["PrcFitness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ProFitness {
            get {
                return ((int)(this["ProFitness"]));
            }
            set {
                this["ProFitness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.01")]
        public float AverageFitnessThreshold {
            get {
                return ((float)(this["AverageFitnessThreshold"]));
            }
            set {
                this["AverageFitnessThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int IfsGenerationMultiplier {
            get {
                return ((int)(this["IfsGenerationMultiplier"]));
            }
            set {
                this["IfsGenerationMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float SelectionPressure {
            get {
                return ((float)(this["SelectionPressure"]));
            }
            set {
                this["SelectionPressure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float MutationProbability {
            get {
                return ((float)(this["MutationProbability"]));
            }
            set {
                this["MutationProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float MutationRange {
            get {
                return ((float)(this["MutationRange"]));
            }
            set {
                this["MutationRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float RandomMutationProbability {
            get {
                return ((float)(this["RandomMutationProbability"]));
            }
            set {
                this["RandomMutationProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public float ControlledMutationProbability {
            get {
                return ((float)(this["ControlledMutationProbability"]));
            }
            set {
                this["ControlledMutationProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public float ArithmeticCrossoverProbability {
            get {
                return ((float)(this["ArithmeticCrossoverProbability"]));
            }
            set {
                this["ArithmeticCrossoverProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float OnePointCrossoverProbability {
            get {
                return ((float)(this["OnePointCrossoverProbability"]));
            }
            set {
                this["OnePointCrossoverProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public float DiscreteSingelRecombinationProbability {
            get {
                return ((float)(this["DiscreteSingelRecombinationProbability"]));
            }
            set {
                this["DiscreteSingelRecombinationProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int EliteIndividualsPerDegree {
            get {
                return ((int)(this["EliteIndividualsPerDegree"]));
            }
            set {
                this["EliteIndividualsPerDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLowerLimitFitnessAdjustment {
            get {
                return ((bool)(this["UseLowerLimitFitnessAdjustment"]));
            }
            set {
                this["UseLowerLimitFitnessAdjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseUpperLimitFitnessAdjustment {
            get {
                return ((bool)(this["UseUpperLimitFitnessAdjustment"]));
            }
            set {
                this["UseUpperLimitFitnessAdjustment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UpdateProbabilityVectorAfterNGenerations {
            get {
                return ((int)(this["UpdateProbabilityVectorAfterNGenerations"]));
            }
            set {
                this["UpdateProbabilityVectorAfterNGenerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public float ProbabilityVectorMinimum {
            get {
                return ((float)(this["ProbabilityVectorMinimum"]));
            }
            set {
                this["ProbabilityVectorMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int DrawImageEveryNthGeneration {
            get {
                return ((int)(this["DrawImageEveryNthGeneration"]));
            }
            set {
                this["DrawImageEveryNthGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExtremeDebugging {
            get {
                return ((bool)(this["ExtremeDebugging"]));
            }
            set {
                this["ExtremeDebugging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Generate5xIndividualsAtInitialization {
            get {
                return ((bool)(this["Generate5xIndividualsAtInitialization"]));
            }
            set {
                this["Generate5xIndividualsAtInitialization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool N2IndividualsFromExistingPoolOfSingels {
            get {
                return ((bool)(this["N2IndividualsFromExistingPoolOfSingels"]));
            }
            set {
                this["N2IndividualsFromExistingPoolOfSingels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseReinsertion {
            get {
                return ((bool)(this["UseReinsertion"]));
            }
            set {
                this["UseReinsertion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecalculateFitnessAfterReinsertion {
            get {
                return ((bool)(this["RecalculateFitnessAfterReinsertion"]));
            }
            set {
                this["RecalculateFitnessAfterReinsertion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float ParentsReinserted {
            get {
                return ((float)(this["ParentsReinserted"]));
            }
            set {
                this["ParentsReinserted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public float OffspringReinserted {
            get {
                return ((float)(this["OffspringReinserted"]));
            }
            set {
                this["OffspringReinserted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeneticUniversumAtRandom {
            get {
                return ((bool)(this["GeneticUniversumAtRandom"]));
            }
            set {
                this["GeneticUniversumAtRandom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MigrationFrequency {
            get {
                return ((int)(this["MigrationFrequency"]));
            }
            set {
                this["MigrationFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MigrationRatePerDegree {
            get {
                return ((int)(this["MigrationRatePerDegree"]));
            }
            set {
                this["MigrationRatePerDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64000")]
        public int InitialSingelPoolSize {
            get {
                return ((int)(this["InitialSingelPoolSize"]));
            }
            set {
                this["InitialSingelPoolSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InitialPopulationFromTextFile {
            get {
                return ((bool)(this["InitialPopulationFromTextFile"]));
            }
            set {
                this["InitialPopulationFromTextFile"] = value;
            }
        }
    }
}
